# version: "3.8" # กำหนด docker version
services:
  # node-server:
  #   container_name: node-js
  #   build: .
  #   ports:
  #     - "8000:8000"
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: repairo
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - repairo_pg_data:/var/lib/postgresql/data

volumes:
  repairo_pg_data:
